name: bibo_exe

on:
  schedule:
    - cron: '0 16 * * 1-5' #1300EST M-F ?
#    - cron: '40 18 * * *' #13:50 PM MDT / 19:45 UTC

  workflow_dispatch:

jobs:
  run-bot:
    environment: alpaca_bibo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PAPERACC: ${{ secrets.PAPERACC }}
          LIVEACC: ${{ secrets.LIVEACC }}
          PAPERACCUUID: ${{ secrets.PAPERACCUUID }}
          ACCUUID: ${{ secrets.ACCUUID }}
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python algorithm/BIBO/main.py
